### ISSUE TITLE
Problem with : org.owasp.csrfguard.CsrfGuardServletContextListener ?

### ISSUE THREAD

**Issue by elbadsi** [OWASP/www-project-csrfguard#19]
When i run my project using eclipse i have this error :

juil. 07, 2021 3:43:34 PM org.apache.catalina.core.StandardContext listenerStart
GRAVE: Exception lors de l'envoi de l'évènement contexte initialisé (context initialized) à l'instance de classe d'écoute (listener) org.owasp.csrfguard.CsrfGuardServletContextListener
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.owasp.csrfguard.CsrfGuardServletContextListener.contextInitialized(CsrfGuardServletContextListener.java:81)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	... 10 more

**Comment by forgedhallpass** [comment]
The problem is at your side. `NoClassDefFoundError` means that the class was found at compile time, but not at runtime. You can see in the `pom.xml`, `org.apache.commons:commons-lang3` is added as a compile time dependency. You can check the packaged libraries in your WAR, and can use `mvn dependency:tree` to figure out what causes the issue. As mentioned in the previous issue, you can also play around with the test application if needed.

**Comment by forgedhallpass** [comment]
A friendly reminder: if you don't use the issue templates to describe your problems, your next ticket will be automatically closed.

**Comment by elbadsi** [comment]
thank you so much for your support :) and i'm sorry for the template.
