### ISSUE TITLE
CsrfGuard.regexpPatternCache is not thread safe

### ISSUE THREAD

**Issue by kguelzau** [OWASP/www-project-csrfguard#96]
**Describe the bug**
CsrfValidator.isUriRegexMatch() is not thread safe since CsrfGuard uses a non concurrent regexpPatternCache.

[private final Map<String, Pattern> regexPatternCache = new HashMap<>();](https://github.com/OWASP/www-project-csrfguard/blob/master/csrfguard/src/main/java/org/owasp/csrfguard/CsrfGuard.java#L64)

```
java.util.ConcurrentModificationException: null
      at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
      at org.owasp.csrfguard.CsrfValidator.isUriRegexMatch(CsrfValidator.java:190)
      at org.owasp.csrfguard.CsrfValidator.isUriMatch(CsrfValidator.java:179)
      at org.owasp.csrfguard.CsrfValidator.isUriMatch(CsrfValidator.java:132)
      at org.owasp.csrfguard.CsrfValidator.isProtectedPage(CsrfValidator.java:93)
      at org.owasp.csrfguard.CsrfValidator.isProtectedPageAndMethod(CsrfValidator.java:79)
      at org.owasp.csrfguard.CsrfValidator.isProtectedPageAndMethod(CsrfValidator.java:145)
      at org.owasp.csrfguard.CsrfValidator.isValid(CsrfValidator.java:65)
      at org.owasp.csrfguard.CsrfGuardFilter.handleNoSession(CsrfGuardFilter.java:111)
      at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:82)
      at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:61)
```

Switching to ConcurrentHashMap should do the Job.

**Comment by forgedhallpass** [comment]
Hello @kguelzau,

Thanks for the observation. Would you like to contribute to the code by creating a PR?
